name: x_taxi_app_client
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  bloc: ^9.0.0
  cloud_firestore: ^5.6.0
  cloud_functions: ^5.2.0
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  firebase_storage: ^12.3.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_image_compress: ^2.4.0
  flutter_pdfview: ^1.4.0
  flutter_svg: ^2.0.16
  fluttertoast: ^8.2.10
  http: ^1.2.2
  intl: ^0.20.2
  path: 1.9.1
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  shared_preferences: ^2.5.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/fonts/
    - assets/json/

  fonts:
    - family: JosefinSlab/JosefinSlab
      fonts:
        - asset: assets/fonts/JosefinSlab/JosefinSlab.ttf
          weight: 300
        - asset: assets/fonts/JosefinSlab/JosefinSlab-Medium.ttf
          weight: 500
        - asset: assets/fonts/JosefinSlab/JosefinSlab-Bold.ttf
          weight: 700

    - family: JosefinSans
      fonts:
        - asset: assets/fonts/JosefinSans/JosefinSans.ttf
          weight: 300
        - asset: assets/fonts/JosefinSans/JosefinSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/JosefinSans/JosefinSans-Bold.ttf
          weight: 700
