// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2zAmrNwjNqkm0fEZQOU5cm41rs9eT4Po',
    appId: '1:385857529512:web:03b82dd153b331fd8e849d',
    messagingSenderId: '385857529512',
    projectId: 'x-taxi-app',
    authDomain: 'x-taxi-app.firebaseapp.com',
    storageBucket: 'x-taxi-app.firebasestorage.app',
    measurementId: 'G-DP6GJ4HRX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBel4slf39PSG7f2lCxMqLSvNO8fUdnAPU',
    appId: '1:385857529512:android:864970dcce3398358e849d',
    messagingSenderId: '385857529512',
    projectId: 'x-taxi-app',
    storageBucket: 'x-taxi-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTeA6HLBayKfuxB3oGnYAwe5wWHiMzThw',
    appId: '1:385857529512:ios:6ee56c318881c5d78e849d',
    messagingSenderId: '385857529512',
    projectId: 'x-taxi-app',
    storageBucket: 'x-taxi-app.firebasestorage.app',
    iosBundleId: 'com.example.xTaxiAppClient',
  );
}
